/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package programasyejercicios;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class LibraryTest {
    @org.junit.jupiter.api.Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(),"someLibraryMethod should return 'true'");
    }
}
